version: "3"

services:
  web:
    # build: .
    image: 088110255905.dkr.ecr.us-east-1.amazonaws.com/poisson
    volumes:
      - "./data:/app/data"
      - static:/app/static

  nginx:
    image: nginx
    ports:
      - "8888:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - static:/app/static
    depends_on:
      - web

  db:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  static:
  database:
