version: "3"
services:
  web:
    # build: .
    image: 088110255905.dkr.ecr.us-east-1.amazonaws.com/poisson

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    depends_on:
      - web
